name: Bug Report
description: Report bugs and help us.

body:
- type: markdown
  attributes:
     value: |
         ## Bug Description
         Talk about bug. State why it occurs and how it occurs.
- type: textarea
  id: bug

- type: textarea
  id: steps
  attributes:
      label: Steps
      description: Write down the steps to reproduce the problem.

 
